name: Integration
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
    - uses: ryanisaacg/setup-qs-action@v1
      with:
        rust-version: ${{ matrix.rust }}
